version: "3"
services:
  githook:
    build: .
    container_name: githook
    volumes: 
      - ${PROJ_ROOT:-/www}:/app
      - /usr/bin/git:/usr/bin/git
      - ~/.ssh:/home/${UNAME}/.ssh
    working_dir: /app/githook
    networks: 
      - default
    ports: 
      - ${GITHOOK_PORT:-8000}:8000
    restart: always
    logging:
      options:
        max-size: "10m"
    environment: 
      - GITHOOK_MAIL_FROM=${MAIL_FROM:-"Henry TIAN <chariothy@gmail.com>"}
      - GITHOOK_MAIL_TO=${MAIL_TO:-"Henry TIAN <chariothy@gmail.com>"}
      - GITHOOK_SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
      - GITHOOK_SMTP_PORT=${SMTP_PORT:-25}
      - GITHOOK_SMTP_USER=${SMTP_USER:-chariothy@gmail.com}
      - GITHOOK_SMTP_PWD=${SMTP_PWD}
      - GITHOOK_PROJECT_BASE_DIR=/app
      - GITHOOK_NOTIFY_MAIL=1
      - GITHOOK_NOTIFY_DINGTALK=1
      - GITHOOK_DINGTALK_TOKEN=${DINGTALK_TOKEN}
      - GITHOOK_DINGTALK_SECRET=${DINGTALK_SECRET}
      - ENV=${ENV}
    command: python main.py
